apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: autoops-elastic-agent
    app.kubernetes.io/component: autoops
    app.kubernetes.io/name: autoops-elastic-agent
    app.kubernetes.io/version: git-2ac617dac96b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: autoops-elastic-agent
      app.kubernetes.io/instance: autoops-elastic-agent
      app.kubernetes.io/name: autoops-elastic-agent
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: autoops-elastic-agent
        app.kubernetes.io/component: autoops
        app.kubernetes.io/instance: autoops-elastic-agent
        app.kubernetes.io/name: autoops-elastic-agent
    spec:
      containers:
        - args:
            - '--config'
            - otel_samples/autoops_es.yml
          env:
            - name: AUTOOPS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: autoops-secret
                  key: autoops-token
            - name: AUTOOPS_ES_URL
              valueFrom:
                secretKeyRef:
                  name: autoops-secret
                  key: autoops-es-url
            - name: RESOURCE_ID
              valueFrom:
                secretKeyRef:
                  name: autoops-secret
                  key: resource-id
            - name: AUTOOPS_TEMP_RESOURCE_ID
              valueFrom:
                secretKeyRef:
                  name: autoops-secret
                  key: temp-resource-id
            - name: AUTOOPS_OTEL_URL
              valueFrom:
                secretKeyRef:
                  name: autoops-secret
                  key: autoops-otel-url
            - name: ELASTICSEARCH_READ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: autoops-secret
                  key: es-username
            - name: ELASTICSEARCH_READ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: autoops-secret
                  key: es-password
          image: >-
            docker.elastic.co/elastic-agent/elastic-otel-collector-wolfi:9.1.0-SNAPSHOT
          imagePullPolicy: Always
          name: autoops-elastic-agent
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
